---
langs: [fr_FR,en_US,es_ES]
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-feed
exclude:
- vendor
plugins:
- jekyll-seo-tag
- jekyll-feed
title: "Documentation Jeedom-Plugins-Extra"
description: "Ceci est la documentation de la team Jeedom-Plugins-Extra."
author: "Jeedom-Plugins-Extra"
image: https://avatars1.githubusercontent.com/u/36200380?s=200&v=4
social:
  name: Jeedom-Plugin-Extra
  links:
    - https://github.com/jeedom-Plugins-Extra
